package io.github.simonbas.screwbox.core.entities;

public enum SystemOrder {
    OPTIMIZATION,
    PREPARATION,
    SIMULATION_BEGIN,
    SIMULATION,
    SIMULATION_LATE,
    PRESENTATION_PREPARE,
    PRESENTATION_BACKGROUND,
    PRESENTATION_WORLD,
    PRESENTATION_EFFECTS,
    PRESENTATION_LIGHT,
    PRESENTATION_OVERLAY,
    PRESENTATION_TRANSITIONS,
    PRESENTATION_UI_BACKGROUND,
    PRESENTATION_UI,
    PRESENTATION_UI_FOREGROUND
}
