package io.github.srcimon.screwbox.core.environment;

public enum SystemOrder {
    OPTIMIZATION,
    PREPARATION,
    PARTICLES_CREATE,
    PARTICLES_CUSTOMIZE,
    PARTICLES_SPAWN,
    SIMULATION_BEGIN,
    SIMULATION,
    SIMULATION_LATE,
    PRESENTATION_PREPARE,
    PRESENTATION_BACKGROUND,
    PRESENTATION_WORLD,
    PRESENTATION_EFFECTS,
    PRESENTATION_LIGHT,
    PRESENTATION_OVERLAY,
    PRESENTATION_TRANSITIONS,
    PRESENTATION_UI_BACKGROUND,
    PRESENTATION_UI,
    PRESENTATION_UI_FOREGROUND
}
