package de.suzufa.screwbox.core.entityengine;

public enum UpdatePriority {
    OPTIMITATION,
    PREPARATION,
    SIMULATION_BEGIN,
    SIMULATION,
    SIMULATION_LATE,
    PRESENTATION_PREPARE,
    PRESENTATION_BACKGROUND,
    PRESENTATION_WORLD_BACKGROUND,
    PRESENTATION_LIGHT,
    PRESENTATION_WORLD,
    PRESENTATION_EFFECTS,
    PRESENTATION_OVERLAY,
    PRESENTATION_TRANSITIONS,
    PRESENTATION_UI_BACKGROUND,
    PRESENTATION_UI,
    PRESENTATION_UI_FOREGROUND;
}
